### PR TITLE
fix: vpc data full output on first apply

### PR DESCRIPTION
**Pull request by jor2**
### Description

vpc_data: output var in patterns vsi module does not give complete output on first apply

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/777

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

fix for vpc_data: output var in patterns vsi module does not give complete output on first apply.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
Perhaps we could add a test which would of caught this. For example take a look at the logic [here](https://github.com/terraform-ibm-modules/terraform-ibm-mas/blob/6ed2eda03f34bd579c33b1318aa1b935877dbe50/tests/pr_test.go#L157-L160) which is checking the output of the code that runs in the test to ensure it contains certain values.

**Comment by surajsbharadwaj** [comment]
Hello Team,

Any target date for this to get fixed ? Our new architecture relies on the subnet groups ids required for VPN and ALB creation.

**Comment by jor2** [comment]
> Hello Team,
> 
> Any target date for this to get fixed ? Our new architecture relies on the subnet groups ids required for VPN and ALB creation.

Hi @surajsbharadwaj, sorry for the delay I was on holidays last week. I'll get it reviewed and hopefully merged and released tomorrow.

**Comment by jor2** [comment]
> Perhaps we could add a test which would of caught this. For example take a look at the logic [here](https://github.com/terraform-ibm-modules/terraform-ibm-mas/blob/6ed2eda03f34bd579c33b1318aa1b935877dbe50/tests/pr_test.go#L157-L160) which is checking the output of the code that runs in the test to ensure it contains certain values.

`vpc_data` previously wasn't included in the outputs for the `default` example. Now that it is included won't `RunTestConsistency` catch if there is an issue on reapply?

**Comment by surajsbharadwaj** [comment]
@jor2 welcome thank. Thank you for prioritising this work. :)

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
