### PR TITLE
fix: extend the vpc output data

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Need few extra information of vpc in the slz to create a output in SLZ. As per this [Issue](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/605)

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Adding a detailed vpc output.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by shemau — APPROVED** [review]
The code looks fine, so I am approving. The one question, why expose a limited (and arbitrary?) set of VPC properties, as opposed to just exposing ibm_is_vpc.vpc and providing the full information to the module consumer?

**Comment by Aashiq-J** [comment]
@shemau , I'm not sure why it wasn't done before. I thought there would be some sensitive information in the output so added only limited values. Now I checked there are no sensitive values so exposing the output of ibm_is_vpc.vpc

**Review by shemau — APPROVED** [review]
LGTM

**Pull request merged**
