### PR TITLE
feat: manual resolver and example

### PR DESCRIPTION
**Pull request by rajatagarwal-ibm**
### Description

* Option to create a manual resolver
* Added validations and flags
* Example
* Tests

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by rajatagarwal-ibm** [comment]
@vburckhardt FYI

when I try to spin up "delegated" service - it says only system and manual are allowed. See the message below:
```
│         "errors": [
│             {
│                 "code": "validation_failed_oneof",
│                 "message": "Expected only one oneOf fields to be set: got 0",
│                 "target": {
│                     "name": "VpcdnsResolverPrototype",
│                     "type": "field"
│                 }
│             },
│             {
│                 "code": "validation_failed_enum",
│                 "message": "VpcdnsResolverTypeManualPrototype is invalid: Validation Failure: Expected [\"manual\"]",
│                 "target": {
│                     "name": "VpcdnsResolverTypeManualPrototype.VpcdnsResolverTypeManualPrototypeType",
│                     "type": "field",
│                     "value": "\"delegated\""
│                 }
│             },
│             {
│                 "code": "validation_failed_enum",
│                 "message": "VpcdnsResolverTypeSystemPrototype is invalid: Validation Failure: Expected [\"system\"]",
│                 "target": {
│                     "name": "VpcdnsResolverTypeSystemPrototype.VpcdnsResolverTypeSystemPrototypeType",
│                     "type": "field",
│                     "value": "\"delegated\""
│                 }
│             }
│         ],
│         "trace": "ee4a6b58-4f91-4274-a3cf-1c23baa37a11"
│     }
│ }
│  
│ 
│   with module.spoke_vpc.ibm_is_vpc.vpc,
│   on ../../main.tf line 29, in resource "ibm_is_vpc" "vpc":
│   29: resource "ibm_is_vpc" "vpc" {
│ 
╵
```

It also says that "dns" is invitation-only service. Not sure if that might be the reason behind not supporting "delegated" service (docs: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_vpc#dns)
image

**Comment by rajatagarwal-ibm** [comment]
Ran both pr_tests and other_tests locally and they passed successfully.

**Review by vburckhardt — APPROVED** [review]

**Pull request merged**
